### ISSUE TITLE
HTTPS is broken?

### ISSUE THREAD

**Issue by domdomegg** [MiBioSoft2017/ProtoCat4#17]
Well, I don't know whether HTTPS is broken or was never supported. Either way, HTTPS [should be supported](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https), and it's [free](https://letsencrypt.org/) to do so now.

Noticed it because the 2016 [results page](http://2016.igem.org/Team:Michigan_Software/Results) you used a HTTPS link which doesn't work now.

Your project & the fact it already has an API is really useful for me either way, so thank you :smile_cat:

**Comment by aturfah** [comment]
We've just started working on getting https supported, thank you for bringing that to our attention

Also we're glad you've liked ProtoCat! 🐱

**Comment by ThomasCOliver** [comment]
It now supports HTTPS, sorry it took so long. Had a bit of a firewall issue that caused us a bit of trouble. We are going to keep this issue open for now until we make the script to autorenew our certificate. Once again, thanks for your interest in our software!

**Comment by domdomegg** [comment]
Awesome, looks to be all working. Thanks :)
