### ISSUE TITLE
Protocols.io API Conversion tool

### ISSUE THREAD

**Issue by ThomasCOliver** [MiBioSoft2017/ProtoCat4#6]
Conversion tool for converting protocols from the file format of protocols.io to that of protocat.

TODO:
Build logic (DONE)
Design UI to do the upload or take the link
Integrate it with the backend

**Comment by aturfah** [comment]
https://github.com/MiBioSoft2017/ProtoCat4/commit/dee84531748fa96a6e4f882417be1165a59e2e35

Logic has been built as a standalone script, moving it into the API now
