### ISSUE TITLE
Improve Search Algorithm

### ISSUE THREAD

**Issue by ThomasCOliver** [MiBioSoft2017/ProtoCat4#8]

**Comment by jgconti96** [comment]
If there are no results from search, display "No results".

**Comment by ThomasCOliver** [comment]
Merged in changes for searching in more fields fcfe6d2a9deecbd1745bee8162ebf7ab8549b379,
will still want to add full-text search later.

**Comment by aturfah** [comment]
Done for Now

**Comment by domdomegg** [comment]
I'm working on a tool that uses Protocat's API, a search API call that would return data like `/api/protocol`, just narrowed down to search matches ~~would be really useful for my project (and probably a lot of others).~~ EDIT: I've got around this, but it would still be a nice to have feature

Ideally it would be a fuzzy search - there are lots of libraries to do this e.g [FuzzyWuzzy](https://github.com/seatgeek/fuzzywuzzy)
